# Generated by Django 3.1.2 on 2021-01-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190201_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='formula',
            field=models.CharField(blank=True, max_length=255, verbose_name='モデル式'),
        ),
        migrations.AddField(
            model_name='comment',
            name='value',
            field=models.IntegerField(blank=True, default=0, verbose_name='数値'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='因子名'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, verbose_name='推定テーマ'),
        ),
    ]
