# Generated by Django 3.1.2 on 2021-01-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210115_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='formula',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='モデル式'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='value',
            field=models.IntegerField(blank=True, null=True, verbose_name='数値'),
        ),
    ]
