# Generated by Django 3.1.2 on 2021-01-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210115_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='formula',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='モデル式'),
        ),
    ]
