# Generated by Django 3.1.2 on 2021-01-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_formula'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='formula_out',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='表示用式'),
        ),
        migrations.AddField(
            model_name='post',
            name='formula_out',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='表示用式'),
        ),
    ]
