# Generated by Django 3.1.2 on 2021-01-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210116_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='value',
            field=models.IntegerField(blank=True, null=True, verbose_name='結果'),
        ),
    ]
