# Generated by Django 3.1.2 on 2021-01-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comment_sub_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='sub_name',
        ),
        migrations.AlterField(
            model_name='comment',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='数値'),
        ),
        migrations.AlterField(
            model_name='post',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='結果'),
        ),
    ]
