# Generated by Django 3.1.2 on 2021-01-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210116_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sub_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='変数名'),
        ),
    ]
