# Generated by Django 3.1.2 on 2021-01-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_comment_sub_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='depth',
            field=models.IntegerField(blank=True, null=True, verbose_name='深さ'),
        ),
    ]
